package br.iesb.mobile.scientificcalculator.constant

//class Constants {
//}

const val One = "1"
const val Two = "2"
const val Three = "3"
const val Four = "4"
const val Five = "5"
const val Six = "6"
const val Seven = "7"
const val Eight = "8"
const val Nine = "9"
const val Zero = "0"
const val Coma = "."
const val Addition = "+"
const val Subtraction = "-"
const val Multiply = "*"
const val Division = "÷"
const val Equals = "="
const val ChangeSinal = "+-"
const val Inverse = "1x"
const val Factorial = "!"
const val SquareRoot = "√"
const val Pi = "π"
const val Back = "←"
const val Reset = "AC"
const val Square = "x²"
const val Exponent = "xʸ"
const val Module = "Mod"
const val Percent = "%"
const val Log = "Log"
const val Ln = "Ln"
const val Sin = "Sin"
const val Cos = "Cos"
const val Tan = "Tan"
const val aSin = "aSin"
const val aCos = "aCos"
const val aTan = "aTan"
const val ERROR = "Error"